// Auto-generated manifest mapping condition names to asset folders/filenames.
// Generated by assistant — audited against src/assets/Condition Icons/ and fixed mismatches.

export type ConditionAsset = { folder: 'De-Buffs' | 'Buffs' | 'Combat Status', filename: string }

export const CONDITION_ASSETS: Record<string, ConditionAsset> = {
  'Advantage': { folder: 'Buffs', filename: 'Advantage.png' },
  'Bardic Inspiration': { folder: 'Buffs', filename: 'Bardic Inspiration.png' },
  'Blessed': { folder: 'Buffs', filename: 'Blessed.png' },
  'Baned': { folder: 'De-Buffs', filename: 'Baned.png' },
  'Baned': { folder: 'De-Buffs', filename: 'Baned.png' },
  'Banished': { folder: 'De-Buffs', filename: 'Baned.png' },
  'Blinded': { folder: 'De-Buffs', filename: 'Blinded.png' },
  'Bloodied': { folder: 'Combat Status', filename: 'Bloodied.png' },
  'Charmed': { folder: 'De-Buffs', filename: 'Charmed.png' },
  'Concentration': { folder: 'Combat Status', filename: 'Concentration.png' },
  'Concentrating': { folder: 'Combat Status', filename: 'Concentration.png' },
  'Deafened': { folder: 'De-Buffs', filename: 'Deafened.png' },
  'Difficult Terrain': { folder: 'De-Buffs', filename: 'Difficult Terrain.png' },
  'Disadvantage': { folder: 'De-Buffs', filename: 'Disadvantage.png' },
  'Dominated': { folder: 'De-Buffs', filename: 'Dominated.png' },
  'Faerie Fire': { folder: 'De-Buffs', filename: 'Faerie Fire.png' },
  'Frightened': { folder: 'De-Buffs', filename: 'Frightened.png' },
  'Grappled': { folder: 'De-Buffs', filename: 'Grappled.png' },
  'Hexed': { folder: 'De-Buffs', filename: 'Hexed.png' },
  'Hunters Mark': { folder: 'Buffs', filename: 'Hunters Mark.png' },
  'Incapacitated': { folder: 'De-Buffs', filename: 'Incapacitated.png' },
  'Invisible': { folder: 'De-Buffs', filename: 'Invisible.png' },
  'Mirror Image': { folder: 'Buffs', filename: 'Mirror Image.png' },
  'Paralyzed': { folder: 'De-Buffs', filename: 'Paralyzed.png' },
  'Petrified': { folder: 'De-Buffs', filename: 'Petrified.png' },
  'Poisoned': { folder: 'De-Buffs', filename: 'Poisoned.png' },
  'Prone': { folder: 'De-Buffs', filename: 'Prone.png' },
  'Raging': { folder: 'Buffs', filename: 'Raging.png' },
  'Restrained': { folder: 'De-Buffs', filename: 'Restrained.png' },
  'Restrained (Spell)': { folder: 'De-Buffs', filename: 'Restrained.png' },
  'Sanctuary': { folder: 'Buffs', filename: 'Sanctuary.png' },
  'Slowed': { folder: 'De-Buffs', filename: 'Slowed.png' },
  'Stunned': { folder: 'De-Buffs', filename: 'Stunned.png' },
  'Surprised': { folder: 'Combat Status', filename: 'Surprised.png' },
  'Unconscious': { folder: 'De-Buffs', filename: 'Unconscious.png' },
  'Hexed': { folder: 'De-Buffs', filename: 'Hexed.png' },
  'Banished': { folder: 'De-Buffs', filename: 'Baned.png' },
}

export const TAB_CONDITIONS = ['Baned', 'Baned', 'Banished', 'Banished', 'Blinded', 'Charmed', 'Deafened', 'Difficult Terrain', 'Disadvantage', 'Dominated', 'Faerie Fire', 'Frightened', 'Grappled', 'Hexed', 'Hexed', 'Incapacitated', 'Invisible', 'Paralyzed', 'Petrified', 'Poisoned', 'Prone', 'Restrained', 'Restrained (Spell)', 'Slowed', 'Stunned', 'Unconscious']
export const TAB_BOONS = ['Advantage', 'Bardic Inspiration', 'Blessed', 'Hunters Mark', 'Mirror Image', 'Raging', 'Sanctuary']
export const TAB_COMBAT = ['Bloodied', 'Concentrating', 'Concentration', 'Surprised']
