// Auto-generated manifest mapping condition names to asset folders/filenames.
// Generated by assistant on 2026-06-07 — keeps filenames with extensions so frontend can prefer webp via ConditionImage.

export type ConditionAsset = { folder: 'De-Buffs' | 'Buffs' | 'Combat Status', filename: string }

export const CONDITION_ASSETS: Record<string, ConditionAsset> = {
  'Advantage': { folder: 'Buffs', filename: 'Advantage.png' },
  'Bardic Inspiration': { folder: 'Buffs', filename: 'Bardic Inspiration.png' },
  'Blessed': { folder: 'Buffs', filename: 'Blessed.png' },
  'Baned': { folder: 'De-Buffs', filename: 'Baned.png' },
  'Baned': { folder: 'De-Buffs', filename: 'Baned.png' },
  'Banished': { folder: 'De-Buffs', filename: 'Baned.png' },
  'Blinded': { folder: 'De-Buffs', filename: 'Blinded.png' },
  'Bloodied': { folder: 'Combat Status', filename: 'Bloodied.png' },
  'Charmed': { folder: 'De-Buffs', filename: 'Charmed.png' },
  'Concentration': { folder: 'Combat Status', filename: 'Concentration.png' },
  'Concentrating': { folder: 'Combat Status', filename: 'Concentration.png' },
  'Deafened': { folder: 'De-Buffs', filename: 'Deafened.png' },
  'Difficult Terrain': { folder: 'De-Buffs', filename: 'Difficult Terrain.png' },
  'Disadvantage': { folder: 'De-Buffs', filename: 'Disadvantage.png' },
  'Dominated': { folder: 'De-Buffs', filename: 'Dominated.png' },
  'Faerie Fire': { folder: 'De-Buffs', filename: 'Faerie Fire.png' },
  'Frightened': { folder: 'De-Buffs', filename: 'Frightened.png' },
  'Grappled': { folder: 'De-Buffs', filename: 'Grappled.png' },
  'Hexed': { folder: 'De-Buffs', filename: 'Hexed.png' },
  'Hunters Mark': { folder: 'Buffs', filename: 'Hunters Mark.png' },
  'Incapacitated': { folder: 'De-Buffs', filename: 'Incapacitated.png' },
  'Invisible': { folder: 'De-Buffs', filename: 'Invisible.png' },
  'Mirror Image': { folder: 'Buffs', filename: 'Mirror Image.png' },
  'Paralyzed': { folder: 'De-Buffs', filename: 'Paralyzed.png' },
  'Petrified': { folder: 'De-Buffs', filename: 'Petrified.png' },
  'Poisoned': { folder: 'De-Buffs', filename: 'Poisoned.png' },
  'Prone': { folder: 'De-Buffs', filename: 'Prone.png' },
  'Push': { folder: 'De-Buffs', filename: 'Push.png' },
  'Raging': { folder: 'Buffs', filename: 'Raging.png' },
  'Restrained': { folder: 'De-Buffs', filename: 'Restrained.png' },
  'Restrained (Spell)': { folder: 'De-Buffs', filename: 'Restrained.png' },
  'Sanctuary': { folder: 'Buffs', filename: 'Sanctuary.png' },
  'Slowed': { folder: 'De-Buffs', filename: 'Slowed.png' },
  'Stunned': { folder: 'De-Buffs', filename: 'Stunned.png' },
  'Surprised': { folder: 'Combat Status', filename: 'Surprised.png' },
  'Topple': { folder: 'De-Buffs', filename: 'Topple.png' },
  'Unconscious': { folder: 'De-Buffs', filename: 'Unconscious.png' },
  'Vex': { folder: 'De-Buffs', filename: 'Vex.png' },
  'Graze': { folder: 'De-Buffs', filename: 'Graze.png' },
  'Cleave': { folder: 'De-Buffs', filename: 'Cleave.png' },
  'Nick': { folder: 'De-Buffs', filename: 'Nick.png' },
  'Silenced': { folder: 'De-Buffs', filename: 'Silenced.png' },
  'Hexed': { folder: 'De-Buffs', filename: 'Hexed.png' },
  'Banished': { folder: 'De-Buffs', filename: 'Baned.png' }
}

export const TAB_CONDITIONS = Object.keys(CONDITION_ASSETS).filter(name => CONDITION_ASSETS[name].folder === 'De-Buffs').sort((a,b)=>a.localeCompare(b))
export const TAB_BOONS = Object.keys(CONDITION_ASSETS).filter(name => CONDITION_ASSETS[name].folder === 'Buffs').sort((a,b)=>a.localeCompare(b))
export const TAB_COMBAT = Object.keys(CONDITION_ASSETS).filter(name => CONDITION_ASSETS[name].folder === 'Combat Status').sort((a,b)=>a.localeCompare(b))
